### ISSUE TITLE
EPIC: Documentation and resources

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/labs#44]
- [x] zOS MVP announcement blog post.
- [x] zOS landing update
- [x] documentation
- [x] README
- [x] talk for ETHBA
- [x] Demo/sample apps in ropsten:
  - [x] Basil
  - [x] Crafty
- [x] Deploy demo apps in mainnet:
  - [x] Basil
  - [x] Crafty
- [x] Onboarding guide (for app developers)
- [x] Migration guide from legacy to upgradeable contracts
- [x] Kernel guide (how to register new versions, how to vouch, etc)

Central doc site:
- [x] Central doc site setup https://github.com/zeppelinos/labs/issues/103
- [x] Include inline contracts documentation from zos-lib in central doc site
- [x] Include documentation from cli (if applies) (see zeppelinos/zos-docs#8)
- [x] quickstart (https://github.com/zeppelinos/zos-cli/issues/127)
- [x] building upgradeable apps guide (https://github.com/zeppelinos/zos-docs/issues/23)
- [x] building apps that use the deployed stdlib (https://github.com/zeppelinos/zos-docs/issues/18)
- [x] stdlib development guide update with new commands (https://github.com/zeppelinos/zos-cli/issues/125)
- [x] testing guide (https://github.com/zeppelinos/zos-docs/issues/19)
- [x] remove migrations guide
- [x] remove FAQ (until we have actual FAQs :) )
- [x] Document zos.json and zos.<network>.json files structure (https://github.com/zeppelinos/zos-cli/issues/36)
- [x] Document the reason for using initializers instead of constructors (https://github.com/zeppelinos/zos-lib/issues/89)
- [x] Document why we can't remove state variables (https://github.com/zeppelinos/zos-lib/issues/90)
- [x] Library docs (https://github.com/zeppelinos/zos-docs/issues/11)
- [x] Guides for sample apps:
  - [x] Basil (see zeppelinos/zos-docs#6, zeppelinos/zos-docs/issues/9)
  - [x] Crafty (see zeppelinos/zos-docs#7)
- [x] Update CLI API with latest version (https://github.com/zeppelinos/zos-docs/issues/30)
- [x] Update Lib API with latest version (https://github.com/zeppelinos/zos-docs/issues/63)

Additional tasks:
- [x] remove "Under heavy development" warnings
- [x] `zos-lib` inline documentation checkup (https://github.com/zeppelinos/zos-lib/issues/145)
- [x] Refactor READMEs of repos, minimal, including Security section:
  - [x] cli
  - [x] lib (https://github.com/zeppelinos/zos-lib/issues/140)
- [x] Have high-level concepts should be explained in the central doc site, not just API.
- [x] Include .sol inline docs from lib
- [x] Review decentraland doc site for inspiration
- [x] Review other docusaurus-based projects for inspiration (see who's using it? section in https://docusaurus.io/)
- [x] Check this https://github.com/zeppelinos/zos-lib/pull/95#discussion_r187666467 and fix if needed (should be tackled alongside https://github.com/zeppelinos/labs/issues/114)
- [x] Show how to deploy and upgrade the contracts in a real network (https://github.com/zeppelinos/zos-docs/issues/14)
